# Generated by Django 6.1.1 on 2026-09-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketstatuslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketStatusLog',
        ),
    ]
