# Generated by Django 6.1.1 on 2026-09-10 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_delete_ticketstatuslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='resolved_at',
            new_name='closed_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_resolved', to=settings.AUTH_USER_MODEL),
        ),
    ]
