# Generated by Django 6.1.1 on 2026-09-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_resolved_at_ticket_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
